INSERT INTO customers (name, email, points, password) 
VALUES ('steven', 'steven@mail.com', '1500', '$2b$15$T86sAt5pWEHbRM8zfyPEmOlLpBOSpJ14wQwR0sjPk8dKoNjFsWb4O');

INSERT INTO books (title, writer, cover_image, point, tags)
VALUES
  ('The Catcher in the Rye', 'J.D. Salinger', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 170, '{"fiction"}'),
  ('Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 190, '{"fiction", "essay"}'),
  ('The Lord of the Rings', 'J.R.R. Tolkien', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 210, '{"fiction"}'),
  ('Jane Eyre', 'Charlotte Bronte', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 175, '{"science"}'),
  ('The Hobbit', 'J.R.R. Tolkien', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 165, '{"non-fiction"}'),
  ('Moby Dick', 'Herman Melville', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 195, '{"fiction"}'),
  ('Brave New World', 'Aldous Huxley', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 220, '{"fiction", "essay"}'),
  ('The Odyssey', 'Homer', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 185, '{"essay"}'),
  ('The Picture of Dorian Gray', 'Oscar Wilde', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 175, '{"fiction"}'),
  ('Crime and Punishment', 'Fyodor Dostoevsky', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 200, '{"fiction"}'),
  ('Frankenstein', 'Mary Shelley', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 180, '{"essay"}'),
  ('The Brothers Karamazov', 'Fyodor Dostoevsky', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 210, '{"fiction"}'),
  ('The Stranger', 'Albert Camus', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 190, '{"fiction"}'),
  ('Slaughterhouse-Five', 'Kurt Vonnegut', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 220, '{"fiction"}'),
  ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 205, '{"fiction"}'),
   ('The Great Gatsby', 'F. Scott Fitzgerald', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 150, '{"fiction"}'),
  ('To Kill a Mockingbird', 'Harper Lee', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 180, '{"fiction"}'),
  ('1984', 'George Orwell', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 200, '{"fiction"}'),
  ('Pride and Prejudice', 'Jane Austen', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 160, '{"fiction"}'),
  ('The Alchemist', 'Paulo Coelho', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 175, '{"fiction"}'),
  ('The Hunger Games', 'Suzanne Collins', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 190, '{"fiction"}'),
  ('The Road', 'Cormac McCarthy', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 180, '{"fiction"}'),
  ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 200, '{"fiction"}'),
  ('The Book Thief', 'Markus Zusak', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 210, '{"fiction"}'),
  ('Gone Girl', 'Gillian Flynn', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 195, '{"fiction"}'),
  ('The Help', 'Kathryn Stockett', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 170, '{"fiction"}'),
  ('The Kite Runner', 'Khaled Hosseini', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 185, '{"fiction"}'),
  ('The Secret Life of Bees', 'Sue Monk Kidd', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 165, '{"fiction"}'),
  ('The Fault in Our Stars', 'John Green', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 175, '{"fiction"}'),
  ('Life of Pi', 'Yann Martel', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 215, '{"fiction"}'),
  ('The Martian', 'Andy Weir', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 200, '{"fiction"}'),
  ('A Thousand Splendid Suns', 'Khaled Hosseini', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 180, '{"fiction"}'),
  ('The Night Circus', 'Erin Morgenstern', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 190, '{"fiction"}'),
  ('The Very Hungry Caterpillar', 'Eric Carle', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 180, '{"fiction"}'),
  ('The Da Vinci Code', 'Dan Brown', 'https://images-na.ssl-images-amazon.com/images/I/51Ga5GuElyL._AC_SX184_.jpg', 180, '{"fiction"}');